
CREATE TABLE PUBLIC.USERS1 (
	ID BIGINT NOT NULL IDENTITY,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	ADDRESS VARCHAR(50),
	DATE_CREATED DATE,
	IS_ACTIVE INTEGER DEFAULT 1 NOT NULL,
) ;
--
--
--CREATE TABLE PUBLIC.EMPLOYEES (
--	ID BIGINT IDENTITY,
--	USER_NAME VARCHAR(20),
--	PASSWORD VARCHAR(10),
--	DESCRIPTION VARCHAR(50),
--	"TYPE" BIGINT,
--	CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID)
--) ;
--
--
--CREATE TABLE PUBLIC.MONITORING_TYPE (
--	ID BIGINT NOT NULL,
--	M_TYPE VARCHAR(100) NOT NULL,
--	DESCRIPTION VARCHAR(100) NOT NULL,
--	CONSTRAINT MONITORING_TYPE_PK PRIMARY KEY (ID)
--) ;
--
--CREATE TABLE PUBLIC.USAGE (
--	ID BIGINT NOT NULL IDENTITY,
--	MONITORING_TYPE_ID BIGINT NOT NULL,
--	USER_ID BIGINT NOT NULL,
--	EMPLOYEE_ID BIGINT NOT NULL,
--	MEASUREMENT DOUBLE NOT NULL,
--	DATE_TAKEN DATE NOT NULL,
--	CONSTRAINT USAGE_PK PRIMARY KEY (ID),
--	CONSTRAINT USAGE_EMPLOYEES_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES PUBLIC.EMPLOYEES(ID),
--	CONSTRAINT USAGE_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID),
--	CONSTRAINT USAGE_MONITORING_TYPE_FK FOREIGN KEY (MONITORING_TYPE_ID) REFERENCES PUBLIC.MONITORING_TYPE(ID)
--) ;
--
