

--
--INSERT INTO PUBLIC.MONITORING_TYPE (ID,"M_TYPE",DESCRIPTION) VALUES (
--1,'GAS','gas measured in cubic meters');
--INSERT INTO PUBLIC.MONITORING_TYPE (ID,"M_TYPE",DESCRIPTION) VALUES (
--2,'WATER','water measured in cubic meters');
--INSERT INTO PUBLIC.MONITORING_TYPE (ID,"M_TYPE",DESCRIPTION) VALUES (
--3,'HOT WATER','hot water measured in cubic meters');
--
--INSERT INTO PUBLIC.EMPLOYEES (ID,USER_NAME,PASSWORD,DESCRIPTION,"TYPE") VALUES (
--1,'incasator','1234567890','default incasator',1);
--
INSERT INTO PUBLIC.USERS1 (ID,FIRST_NAME,LAST_NAME,ADDRESS,DATE_CREATED,IS_ACTIVE) VALUES (
1,'John','Doe','vitoshka','2018-12-28',1);

